### ISSUE TITLE
[Rankings] The rankings are not updated

### ISSUE THREAD

**Issue by Kern046** [rtfmcorp/asylamba-game#35]
![classement](https://cloud.githubusercontent.com/assets/6918102/20167539/7f22017a-a71c-11e6-83d1-d8b873eeadaa.png)

**Comment by Kern046** [comment]
These logs are certainly related to the issue : 

```
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined offset: 0 in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 106
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: general in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 106
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: wealth in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 42
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: wealth in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 45
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: wealth in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 42
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: wealth in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 45
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: wealth in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 42
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: wealth in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 45
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: territorial in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 49
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: territorial in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 52
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: territorial in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 49
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: territorial in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 52
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: territorial in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 49
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: territorial in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 52
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: wealth in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 67
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: wealth in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 72
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: territorial in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 67
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: territorial in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 72
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: points in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 56
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: points in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 59
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: points in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 56
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: wealth in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 230
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: territorial in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 234
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: points in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 244
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: points in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 251
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Warning:  Creating default object from empty value in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 251
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Warning:  Creating default object from empty value in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 252
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Notice:  Undefined index: territorial in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 253
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Warning:  Creating default object from empty value in /var/www/html/s12/system/script/scripts/cron/factionRanking.php on line 253
[11-Nov-2016 03:05:01 Europe/Zurich] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'points' cannot be null' in /var/www/html/s12/system/modules/atlas/class/FactionRankingManager.php:132
Stack trace:
#0 /var/www/html/s12/system/modules/atlas/class/FactionRankingManager.php(132): PDOStatement->execute(Array)
#1 /var/www/html/s12/system/script/scripts/cron/factionRanking.php(257): FactionRankingManager->add(Object(FactionRanking))
#2 /var/www/html/s12/system/script/main.php(79): include('/var/www/html/s...')
#3 /var/www/html/s12/system/classes/worker/CTR.class.php(193): include('/var/www/html/s...')
#4 /var/www/html/s12/index.php(54): CTR::getInclude()
#5 {main}
  thrown in /var/www/html/s12/system/modules/atlas/class/FactionRankingManager.php on line 132
```
